# Service descriptions for Dolby CP750

set_fader:
  name: Set Fader
  description: Set the fader level of the Dolby CP750.
  target:
    entity:
      integration: dolby_cp750
  fields:
    value:
      name: Value
      description: Fader level in dB
      required: true
      selector:
        number:
          min: -90.0
          max: 10.0
          step: 0.5
          unit_of_measurement: dB

set_input:
  name: Set Input
  description: Select the input source of the Dolby CP750.
  target:
    entity:
      integration: dolby_cp750
  fields:
    source:
      name: Source
      description: Input source to select
      required: true
      selector:
        select:
          options:
            - "Digital 1"
            - "Digital 2"
            - "Digital 3"
            - "Digital 4"
            - "Multi-Ch Analog"
            - "NonSync"
            - "Mic"

set_mute:
  name: Set Mute
  description: Set the mute state of the Dolby CP750.
  target:
    entity:
      integration: dolby_cp750
  fields:
    mute:
      name: Mute
      description: True to mute, False to unmute
      required: true
      selector:
        boolean: